client_config_backend: file
client_config:
    client_id: 377974340336-d5j20191g9nmj7u9u44vm2qpq4rrkq8b.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive